apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: 282527170177.dkr.ecr.us-east-1.amazonaws.com/promodemoapp:sha256-dee30aa751da9633d38ea403d8512f564fdaaa3bf375ecbf63b9686604751b65.sig
        name: app1
        ports:
        - containerPort: 80
