name: CI - CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PARENT_IMAGE: "gcr.io/distroless/static-debian12@sha256:8cbe18a8a9a9fefe70590dc8f6a7bc70b4bbe41f262d9dab9084337adabf6d26"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build App Img from Dockerfile
        run: |
          docker build --build-arg PARENT_IMG=${{ env.PARENT_IMAGE }} -t ${{ github.repository }}:${{ github.sha }} .
      - name: Save App Img as Artifact
        run: |
          docker save --output ${{ github.workspace }}/${{ github.repository }}.img.tar ${{ github.repository }}:${{ github.sha }} 
      - uses: actions/upload-artifact@v4
        with:
          name: img-artifact-${{ github.repository }}
          path: ${{ github.workspace }}/${{ github.repository }}.img.tar
  DeployDev:
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::282527170177:role/github-dev-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Dev!
  DeployStaging:
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::053353455593:role/github-stage-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Staging!
  DeployProd:
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Prod
      url: 'http://www.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::842572306205:role/github-prod-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Prod!
