name: CI - CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Compile
        run: echo Building!
  DeployDev:
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::282527170177:role/github-dev-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Dev!
  DeployStaging:
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::053353455593:role/github-stage-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Staging!
  DeployProd:
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploying to Staging!
