name: CI - CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PARENT_IMAGE: "gcr.io/distroless/static-debian12@sha256:8cbe18a8a9a9fefe70590dc8f6a7bc70b4bbe41f262d9dab9084337adabf6d26"
  IMG_NAME: "promodemoapp"
  DEV_ACT: "282527170177"
  STAGE_ACT: "053353455593"
  PROD_ACT: "842572306205"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build App Img from Dockerfile
        run: |
          docker build --build-arg PARENT_IMG=${{ env.PARENT_IMAGE }} -t ${{ env.IMG_NAME }}:${{ github.sha }} .
      - name: Save App Img as Artifact
        run: |
          docker save --output ${{ github.workspace }}/${{ env.IMG_NAME }}.img.tar ${{ env.IMG_NAME }}:${{ github.sha }} 
      - uses: actions/upload-artifact@v4
        with:
          name: img-artifact-${{ env.IMG_NAME }}
          path: ${{ github.workspace }}/${{ env.IMG_NAME }}.img.tar
  DeployDev:
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ env.DEV_ACT }}:role/github-dev-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Download Img Tar Artifact
        uses: actions/download-artifact@v4
        with:
          name: img-artifact-${{ env.IMG_NAME }}
          path: ${{ github.workspace }}
      - name: Display Downloaded Img Artifact
        run: ls -R ${{ github.workspace }}
      - name: Load App Img Tar into Docker
        run: |
          docker load -i ${{ github.workspace }}/${{ env.IMG_NAME }}.img.tar
      - name: Tag Docker Local Img
        run: |
          docker image tag ${{ env.IMG_NAME }}:${{ github.sha }} ${{ env.DEV_ACT }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.IMG_NAME }}:${{ github.sha }}
      - name: Display loaded Docker images
        run: |
          docker images
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.IMG_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  DeployStaging:
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ env.STAGE_ACT }}:role/github-stage-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Staging!
  DeployProd:
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: Prod
      url: 'http://www.myapp.com'
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ env.PROD_ACT }}:role/github-prod-role
          role-session-name: github_aws_federated_oidc
          aws-region: us-east-1
      - name: Test AWS Creds
        run: |
          aws sts get-caller-identity
      - name: Deploy
        run: echo Deploying to Prod!
