name: CI - CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Compile
        run: echo Building!
  DeployDev:
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploying to Dev!
  DeployStaging:
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploying to Staging!
  DeployProd:
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploying to Staging!
